#!/bin/sh
mkdir -p dist

NODE_ENV=production node_modules/.bin/browserify lib/index.js \
  -t [reactify --es6] \
  -t browserify-shim \
  -t envify \
  --detect-globals false \
  -s ReactPicture \
  > dist/react-picture.js

node_modules/.bin/uglifyjs dist/react-picture.js \
  --compress \
  warnings=false \
  > dist/react-picture.min.js

echo "gzipped, the global build is:"
echo "`gzip -c dist/react-picture.min.js | wc -c` bytes"

